@echo off
echo Adding files...
git add .
echo Committing changes...
git commit -m "Add new files for sync"
echo Pushing to Gitee...
git push origin main
echo Pushing to GitHub...
git push github main
echo Sync upload completed!
pause